title: Chomp the cheese
hero_image: images/banner.png
description: Make a facial recognition game where you have to eat cheesy puffs that are moving around you
version: 1
listed: false
copyedit: false
last_tested: "2024-07-02"
steps:
  - title: What you will make
  - title: Set up the project
    completion:
      - engaged
  - title: Move the cheese
  - title: Chomp the cheese
    completion:
      - internal
  - title: Challenge
    completion:
      - external
  - title: What can you do now?
