---
title: Cnô'r caws
hero_image: images/banner.png
description: Gwnewch gêm adnabod wynebau lle mae'n rhaid i chi fwyta pwff cawslyd sy'n symud o'ch cwmpas
version: 1
listed: true
copyedit: false
last_tested: "2024-07-02"
steps:
  - title: Beth fyddwch chi'n ei wneud
  - title: Gosodwch y prosiect
    completion:
      - engaged
  - title: Symud y caws
  - title: Cnowch y caws
    completion:
      - internal
  - title: Her
    challenge: true
    completion:
      - external