title: Chomp the cheese
hero_image: images/banner.png
description: Make a facial recognition game where you have to eat cheesy puffs that are moving around you
version: 1
listed: true
copyedit: false
last_tested: "2024-07-02"
steps:
  - 
    title: Das wirst du machen
  - 
    title: Verwende ein vortrainiertes Modell
    completion:
      - engaged
  - 
    title: Move the cheese
  - 
    title: Chomp the cheese
    completion:
      - internal
  - 
    title: Herausforderung
    challenge: true
  - 
    title: Wie geht es weiter?
    completion:
      - external
