title: Morda o queijo
hero_image: images/banner.png
description: Crie um jogo de reconhecimento facial onde você tem que comer cheesy puffs que se movem ao seu redor
version: 1
listed: true
copyedit: false
last_tested: "2024-07-02"
steps:
  - 
    title: O que você vai fazer
  - 
    title: Configurar o projeto
    completion:
      - engaged
  - 
    title: Mova o queijo
  - 
    title: Morda o queijo
    completion:
      - internal
  - 
    title: Desafio
    challenge: true
    completion:
      - externo
